"""bandymas prideti stulpeli

Revision ID: 115bda468aa3
Revises: c41189a8e4bc
Create Date: 2026-09-24 15:39:08.998570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '115bda468aa3'
down_revision: Union[str, Sequence[str], None] = 'c41189a8e4bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentas', sa.Column('el_pastas', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studentas', 'el_pastas')
    # ### end Alembic commands ###
