"""sukurti lentele studentas

Revision ID: c41189a8e4bc
Revises: 
Create Date: 2026-09-24 11:30:17.480458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c41189a8e4bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vardas', sa.String(), nullable=False),
    sa.Column('kursas', sa.Integer(), nullable=True),
    sa.Column('vidurkis', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studentas')
    # ### end Alembic commands ###
